image:
  file: .gitpod.Dockerfile

ports:
  - port: 4000
    onOpen: ignore
  - port: 8000
    onOpen: open-preview

tasks:
  - name: change backend address
    command: |
      sed -i 's/const URL = "http:\/\/clouddisk/\/\/ const URL = "http:\/\/clouddisk/g' /workspace/web_object_detection/js/index.js
      sed -i "/localhost/i\const URL = \"https:\/\/4000-${GITPOD_WORKSPACE_URL:8}/api/\"" js/index.js

  - name: start backend server
    command: python3 /workspace/web_object_detection/app.py

  - name: start forntend server
    command: cd /workspace/web_object_detection/ && python3 -m http.server
