image:
  file: .gitpod.Dockerfile

ports:
  - port: 4000
    onOpen: ignore
  - port: 8000
    onOpen: open-preview
  

tasks:
  - name: change backend address
    command: |
      sed -i 's/\/\/ const URL = "http:\/\/localhost/const URL = "http:\/\/localhost/g' /workspace/web_object_detection/js/index.js
      sed -i 's/const URL = "http:\/\/raspberry/\/\/ const URL = "http:\/\/raspberry/g' /workspace/web_object_detection/js/index.js
      sed -i "s/http:\/\/localhost:4000/https:\/\/4000-${GITPOD_WORKSPACE_URL:8}/g" /workspace/web_object_detection/js/index.js

  - name: start backend server
    command: python3 /workspace/web_object_detection/app.py

  - name: start forntend server
    command: cd /workspace/web_object_detection/ && python3 -m http.server
