name: Docker ci

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        run: |
          echo env.{{GITHUB_WORKSPACE}}
          cat env.{{GITHUB_WORKSPACE}}/js/index.js

      - uses: actions/checkout@v2
      - run: |
          echo env.{{GITHUB_WORKSPACE}}
          cat env.{{GITHUB_WORKSPACE}}/js/index.js

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tsanfer/web_object_detection:latest
      
      # local
      - name: change directory
        uses: actions/checkout@v2
      - name: change backend address
        run: |
          sed -i 's/\/\/ const URL = "http:\/\/localhost/const URL = "http:\/\/localhost/g' env.{{GITHUB_WORKSPACE}}/js/index.js
          sed -i 's/const URL = "http:\/\/raspberry/\/\/ const URL = "http:\/\/raspberry/g' env.{{GITHUB_WORKSPACE}}/js/index.js
          cat env.{{GITHUB_WORKSPACE}}/js/index.js
      - name: Build and push local_version
        id: docker_build_local
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tsanfer/web_object_detection:local
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
