name: ci

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
<<<<<<< HEAD
          tags: tsanfer/web_object_detection:latest
=======
          tags: tsanfer/app:latest
>>>>>>> 97cc6bf8729a00ab31bd36ac05f1c8dcaecf3e3c
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
